const ACCESS_TOKEN_SECRET = 'do8Nts72oPH';
const ACCESS_TOKEN_LIFE = 1200;
const REFRESH_TOKEN_SECRET = 'lcw8QwLyVMf389fO302dWjdwowKweoBid';
const REFRESH_TOKEN_LIFE = 86400;
const CODE_FOR_RECOVERY_TOKEN_SECRET = 'nkaco87wevkbroq'
const RECOVERY_TOKEN_SECRET = 'nkacosdcdcssdc87wevkbroq'

module.exports = {
    ACCESS_TOKEN_SECRET, ACCESS_TOKEN_LIFE, REFRESH_TOKEN_LIFE, REFRESH_TOKEN_SECRET, RECOVERY_TOKEN_SECRET, CODE_FOR_RECOVERY_TOKEN_SECRET
}
