const ACCESS_TOKEN_SECRET = 'do8Nts72oPH';
const ACCESS_TOKEN_LIFE = 1200;
const REFRESH_TOKEN_SECRET = 'lcw8QwLyVMf389fO302dWjdwowKweoBid';
const REFRESH_TOKEN_LIFE = 86400;

module.exports = {
    ACCESS_TOKEN_SECRET, ACCESS_TOKEN_LIFE, REFRESH_TOKEN_LIFE, REFRESH_TOKEN_SECRET
}
